<a href="https://colab.research.google.com/github/anjalisgrl/MyCaptain/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy
 

In [3]:
[[1,2,3],[1,2]]

[[1, 2, 3], [1, 2]]

In [0]:
import numpy as np

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [0]:
lis = [1,2,3]
x = np.array(lis)

In [7]:
print(type(x))

<class 'numpy.ndarray'>


In [0]:
lis1 = [2,4,6]
y = np.array(lis1)

In [9]:
x + y

array([3, 6, 9])

In [10]:
x*y

array([ 2,  8, 18])

In [0]:
z = np.zeros((7,3))

In [13]:
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full((3,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [0]:
x= np.array([[1,2,3],[1,2,4],[2,4,6]])

In [0]:
z = x[2:]

In [18]:
print(z)

[[2 4 6]]


In [20]:
print(x[1:])

[[1 2 4]
 [2 4 6]]


In [21]:
print(x[:1])

[[1 2 3]]


In [22]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [23]:
np.arange(6).reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])